# Assumes the OpenLiberty operator has been installed in your cluster
apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: modresorts
spec:
  applicationImage: image-registry.openshift-image-registry.svc:5000/resorts/infiniresorts:1.6
  replicas: 2
  service:
    type: ClusterIP
    port: 9080
  expose: true
  volumeMounts:
    - mountPath: /platform/bindings/secret/
      readOnly: true
      name: rhdg-secret-volume
  volumes:
    - name: rhdg-secret-volume
      secret:
        secretName: modresorts-cache-generated-secret
  env:
    - name: WLP_LOGGING_CONSOLE_FORMAT
      value: "simple"
