# Assumes the OpenLiberty operator has been installed in your cluster
apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: resorts
spec:
  applicationImage: image-registry.openshift-image-registry.svc:5000/resorts/infiniresorts:1.6
  replicas: 2
  service:
    type: ClusterIP
    port: 9080
  expose: true